##请求处理的超时时间
#ribbon:
#  ReadTimeout: 10000
#  ConnectTimeout: 10000
#
## feign 配置
#feign:
#  hystrix:
#    enabled: true
#  okhttp:
#    enabled: true
#  httpclient:
#    enabled: false
#  client:
#    config:
#      default:
#        connectTimeout: 10000
#        readTimeout: 10000
#  compression:
#    request:
#      enabled: true
#    response:
#      enabled: true
#
## hystrix 配置
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE
#          thread:
#            timeoutInMilliseconds: 60000
#  shareSecurityContext: true

## 认证配置
#security:
#  oauth2:
#    client:
#      client-id: app
#      client-secret: 123456
#      scope: server
#    resource:
#      loadBalanced: true
#      token-info-uri: lb://auth/oauth/check_token
#    ignore:
#      urls:
#        - /v2/api-docs
#        - /actuator/**
#        - /user/info/*
#        - /operlog
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    # 连接池中的最小空闲连接 默认 0
    lettuce:
      pool:
        min-idle: 0
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
      shutdown-timeout: 200ms
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 60s
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: test
          uri: http://www.12306.cn/
          predicates:
            - Path=/**
    sentinel:
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: d0f195c1-58b6-4c73-aaf4-b9a15ab8b8b8
            dataId: ${spring.application.name}-sentinel
            rule-type: gw-flow
            groupId: DEFAULT_GROUP
            data-type: json
      transport:
        dashboard: localhost:8021
        port: 8719
      filter:
        enabled: true
      # 是否饥饿加载。默认为 false 关闭
      eager: true
      # Sentinel 对 Spring Cloud Gateway 的专属配置项，对应 SentinelGatewayProperties 类
      scg:
        order: -2147483648 # 过滤器顺序，默认为 -2147483648 最高优先级
        fallback:
          mode: response # fallback 模式，目前有三种：response、redirect、空
          # 专属 response 模式
          response-status: 429 # 响应状态码，默认为 429
          response-body: 你被 block 了... # 响应内容，默认为空
          content-type: application/json # 内容类型，默认为 application/json
          # 专属 redirect 模式
          redirect: http://www.baidu.com

##动态路由配置
gateway:
  dynamic:
    route:
      enabled: true